const HTML_TAGS = [
  'a', 'address', 'audio', 'b', 'br', 'button', 'col', 'colgroup', 'dd', 'div', 'dl', 'dt', 'em',
  'fieldset', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'i', 'iframe', 'img', 'input',
  'kbd', 'label', 'legend', 'li', 'ol', 'option', 'p', 'polygon', 'select', 'small', 'source',
  'span', 'strong', 'sub', 'svg', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'tr',
  'u', 'ul',
];
const MY_TAGS = [
  'a', 'button',
  'form', 'iframe', 'i', 'img', 'input',
  'label', 'option', 'table', 'tbody', 'thead'
];

const MUI_TAGS = [
  'accordion',
  'accordionactions',
  'accordiondetails',
  'accordionsummary',
  'alert',
  'alerttitle',
  'appbar',
  'autocomplete',
  'avatar',
  'avatargroup',
  'backdrop',
  'badge',
  'bottomnavigation',
  'bottomnavigationaction',
  'box',
  'breadcrumbs',
  'button',
  'buttonbase',
  'buttongroup',
  'card',
  'cardactionarea',
  'cardactions',
  'cardcontent',
  'cardheader',
  'cardmedia',
  'checkbox',
  'chip',
  'circularprogress',
  'clickawaylistener',
  'collapse',
  'container',
  'dialog',
  'dialogactions',
  'dialogcontent',
  'dialogcontenttext',
  'dialogtitle',
  'divider',
  'drawer',
  'fab',
  'fade',
  'filledinput',
  'filledinput',
  'formcontrol',
  'formcontrollabel',
  'formgroup',
  'formhelpertext',
  'formlabel',
  'grid',
  'grow',
  'hidden',
  'iconbutton',
  'imagelist',
  'imagelistitem',
  'imagelistitembar',
  'input',
  'inputadornment',
  'inputbase',
  'inputlabel',
  'linearprogress',
  'link',
  'list',
  'listitem',
  'listitemavatar',
  'listitembutton',
  'listitemicon',
  'listitemsecondaryaction',
  'listitemtext',
  'listsubheader',
  'menu',
  'menuitem',
  'menulist',
  'mobilestepper',
  'modal',
  'nativeselect',
  'outlinedinput',
  'pagination',
  'paginationitem',
  'paper',
  'popover',
  'portal',
  'radio',
  'radiogroup',
  'rating',
  'select',
  'skeleton',
  'slide',
  'slider',
  'snackbar',
  'snackbarcontent',
  'speeddial',
  'speeddialaction',
  'speeddialicon',
  'stack',
  'step',
  'stepbutton',
  'stepconnector',
  'stepcontent',
  'stepicon',
  'steplabel',
  'steplabel',
  'stepper',
  'svgicon',
  'swipeabledrawer',
  'switch',
  'tab',
  'table',
  'tablebody',
  'tablecell',
  'tablecontainer',
  'tablefooter',
  'tablehead',
  'tablepagination',
  'tablerow',
  'tablesortlabel',
  'tabs',
  'tabscrollbutton',
  'textfield',
  'textareaautosize',
  'togglebutton',
  'togglebuttongroup',
  'toolbar',
  'tooltip',
  'typography',
  'zoom',
];

module.exports.HTML_TAGS = HTML_TAGS
module.exports.MY_TAGS = MY_TAGS
module.exports.MUI_TAGS = MUI_TAGS
